global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: petshelter-api
    static_configs:
      - targets: ["petshelter-api:8080"]
    metrics_path: /metrics

  - job_name: vetclinic-api
    static_configs:
      - targets: ["vetclinic-api:8080"]
    metrics_path: /metrics
